.TM LIBROWNIE
.SH RESUMO
Biblioteca do aluno Lucas Lira de Oliveira com funcoes usadas no decorrer do curso
.SH conversao
.PP
.B description:
Funcao que converte duas escalas.
.PP
.B Forma completa:
float conversao(float r1i, float r1f, float r2i, float r2f, float primeiro);
.SH tamanhoString
.PP
.B description:
Funcao que calcula o tamanho de uma string.
.PP
.B Forma completa:
int tamanhoString(char string[]);
.SH prefixo
.PP
.B description:
Funcao que checa se uma palavra e' prefixo da outra.
.PP
.B Forma completa:
_Bool prefixo(char palavra[], char subP[], int num1, int num2);
.SH sufixo
.PP
.B description:
Funcao que checa se uma palavra e' sufixo da outra.
.PP
.B Forma completa:
_Bool sufixo(char palavra[], char subP[], int num1, int num2);
.SH concatenarString
.PP
.B description:
Funcao que concatena duas strings.
.PP
.B Forma completa:
void concatenarStrings(char string1[], int tamanho1, char string2[], int tamanho2, char string3[]);
.SH inverter
.PP
.B description:
Funcao que inverte uma string.
.PP
.B Forma completa:
void inverter(char *string, char *nString, int quantidade);

